services:
  - type: web
    plan: free
    name: TG Rename Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/thankan-kurups/FileRenameBot.git
    branch: master
    autoDeploy: false
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: UPDATE_CHANNEL
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URI
        sync: false
      - key: START_PIC
        sync: false
      - key: ADMIN
        sync: false
      - key: WEBHOOK
        sync: false
      - key: DATABASE_URL
        sync: false
